version: "1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make start
    ports: 
      - "3000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
