CREATE DATABASE redmine WITH ENCODING='UTF8' OWNER=postgres;
GRANT ALL PRIVILEGES ON DATABASE redmine TO postgres;

CREATE DATABASE redmine_test WITH ENCODING='UTF8' OWNER=postgres;
GRANT ALL PRIVILEGES ON DATABASE redmine_test TO postgres;