name: Say hello
on: push

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: say-hello
        run: make say-hello
        working-directory: ./github-actions